Change: server port
logging:
    level:
        blog: WARN
        hibernate:
            type:
                descriptor: TRACE
        org: WARN
        org.hibernate.SQL: DEBUG
        org.hibernate.orm.jdbc.bind: TRACE
        org.springframework.security: TRACE
#server: port = 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ${db_password:}
        url: jdbc:mysql://localhost:3306/the_chef_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
        username: root
    servlet:
      multipart:
          max-file-size: 50MB
          max-request-size: 50MB
    main:
        allow-circular-references: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
    mvc:
        hiddemethod:
            filter:
                enabled: true
    resources:
        cache: 'null'
        period: 0
    sql:
        init:
            mode: never
    thymeleaf:
        cache: false
        encoding: UTF-8
        mode: HTML
        prefix: file:src/main/resources/templates/
